steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/eore-code-generator', '.' ]
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'push', 'gcr.io/$PROJECT_ID/eore-code-generator' ]
  - name: 'gcr.io/cloud-builders/gcloud'
    args: [
      'run', 'deploy', 'eore-code-generator',
      '--image', 'gcr.io/$PROJECT_ID/eore-code-generator',
      '--platform', 'managed',
      '--region', 'asia-southeast1', # Replace with your preferred region
      '--add-cloudsql-instances', '$INSTANCE_CONNECTION_NAME',
      '--allow-unauthenticated'
    ]
